[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mi_conversor"
version = "0.1.0"
description = "Librería sencilla de conversión"
authors = [{name = "Denis Lucian Moran Ochis"}]

[tool.pytest.ini_options]
pythonpath = ["src"]